movie/app1/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views

app_name = "app1"
urlpatterns = [
    path('', views.home, name="home"),
    path('details/<int:p>', views.details, name="details"),
    path('add',views.add_movie,name="add"),
    path('edit/<int:p>',views.edit,name="edit"),
    path('delete/<int:p>',views.delete,name="delete")



]

movie/movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/app1/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    language = models.CharField(max_length=20)
    year = models.IntegerField()
    image = models.ImageField(upload_to="img", blank=True, null=True)

    def __str__(self):
        return self.title

movie/app1/views.py
from django.shortcuts import render, redirect
from app1.models import Movie


# Create your views here.
def home(request):
    k = Movie.objects.all()
    return render(request, 'home.html', {'movie': k})


def add_movie(request):
    if request.method == "POST":
        t = request.POST['t']
        d = request.POST['d']
        l = request.POST['l']
        y = request.POST['y']
        i = request.FILES['i']

        m = Movie.objects.create(title=t, description=d, language=l, year=y, image=i)
        m.save()
        return home(request)
    return render(request, 'add.html')


def details(request, p):
    k = Movie.objects.get(id=p)
    return render(request, 'details.html', {'movie': k})


def edit(request, p):
    k = Movie.objects.get(id=p)
    if request.method == "POST":
        k.title = request.POST['t']
        k.description = request.POST['d']
        k.language = request.POST['l']
        k.year = request.POST['y']
        if request.FILES.get('i') == "None":
            k.save()
        else:
            k.image = request.FILES.get('i')
        k.save()
        return home(request)

    return render(request, 'edit.html', {'movie': k})


def delete(request, p):
    k = Movie.objects.get(id=p)
    k.delete()
    return home(request)

movie/templates/add.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mb-5">
<h2 class="text-center mt-4 mb-3">Add Movies</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
    <label class="form-label">Title</label>
    <input type="text" class="form-control" name="t" placeholder="Enter the Title">
    </div>
    <div class="mb-3">
    <label class="form-label">Description</label>
    <input type="text" class="form-control" name="d" placeholder="Enter the Description">
    </div>
    <div class="mb-3">
    <label class="form-label">Language</label>
    <input type="text" class="form-control" name="l" placeholder="Enter the language">
    </div>
    <div class="mb-3">
    <label class="form-label">Year</label>
    <input type="text" class="form-control" name="y" placeholder="Enter the Year">
    </div>
     <div class="mb-3">
    <label class="form-label">Image</label>
    <input type="file" class="form-control" name="i">
    </div>
    <div class= "mb-3 text-center mt-4">
        <input type="submit" value="ADD MOVIE" class="btn-success">
    </div>
</form>
</div>
{% endblock %}

movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark fw-bold bg-warning">
  <div class="container-fluid">
    <a class="navbar-brand">Online Movie Store</a>
    <form class="d-flex">
      <a class="btn btn-outline-success" href="{% url 'app1:add' %}">Add Movies</a>
    </form>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

movie/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center mt-4 mb-3">Movie Details</h2>
<div class="card mx-auto mb-3 bg-warning text-center" style="max-width: 640px;color:red;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{movie.image.url}}" class="rounded-start p-3" alt="..." height="300px" width="100%">
    </div>
    <div class="col-md-7 mt-4">
      <div class="card-body">
        <h5 class="card-title">{{movie.title}}</h5>
        <p class="card-text">{{movie.description}}</p>
        <p class="card-text">Language: {{movie.language}}</p>
        <p class="card-text">Year: {{movie.year}}</p>
        <a href="{% url 'app1:edit' movie.pk %}" class="btn btn-primary">Update</a>
        <a href="{% url 'app1:delete' movie.pk %}" class="btn btn-primary">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

movie/templates/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center">Edit Movie Details</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
    <label class="form-label">Title</label>
    <input type="text" class="form-control" name="t" value="{{movie.title}}" placeholder="Enter the Title">
    </div>
    <div class="mb-3">
    <label class="form-label">Description</label>
    <input type="text" class="form-control" name="d" value="{{movie.description}}" placeholder="Enter the Description">
    </div>
    <div class="mb-3">
    <label class="form-label">Language</label>
    <input type="text" class="form-control" name="l" value="{{movie.language}}" placeholder="Enter the language">
    </div>
    <div class="mb-3">
    <label class="form-label">Year</label>
    <input type="text" class="form-control" name="y" value="{{movie.year}}" placeholder="Enter the Year">
    </div>
     <div class="mb-3">
    <label class="form-label">Image</label>
         <img src="{{movie.image.url}}" height="100px" width="100px">
    <input type="file" class="form-control" name="i">
    </div>
    <div class="mb-3">
        <input type="submit" value="ADD MOVIE">
    </div>

{% endblock %}

movie/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row mt-5">
        {% for i in movie %}
        <div class="col-sm-4">
            <div class="card mx-auto" style="width: 18rem;">
  <img src="{{i.image.url}}" height="350px" width="100%" class="card-img-top" alt="...">
  <div class="card-body text-center">
    <h5 class="card-title">{{i.title}}</h5>
    <p class="card-text">{{i.year}}</p>
    <a href="{% url 'app1:details' i.id %}" class="btn btn-primary">Details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
    {{name}}
    {{age}}
</div>
{% endblock %}